import { StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { CheckCircle2, CircleAlert } from 'lucide-react-native';
import { Page } from '@/components/page';
import { EmptyState, PrimaryButton } from '@/components/ui';
import { useAuth } from '@/context/auth-context';
import { colors, fonts } from '@/theme/tokens';
export default function AccountScreen(){const {auth,profile,loading,signOut}=useAuth();if(!loading&&!auth)return <Page back><EmptyState title="Sign in required" body="Create an account or sign in to use secure account features." action={<PrimaryButton onPress={()=>router.replace('/sign-in')}>Sign in</PrimaryButton>}/></Page>;return <Page back><Text style={s.title}>Account & security</Text><Text style={s.email}>{auth?.email}</Text><View style={s.card}><Text style={s.name}>{profile?.displayName||'Your account'}</Text><Text style={s.role}>{profile?.role||'member'} · {profile?.status||'loading'}</Text><Status ok={Boolean(profile?.verification.emailVerified)} label="Email verified"/><Status ok={Boolean(profile?.verification.phoneVerified)} label="Phone verified"/></View>{!profile?.verification.phoneVerified&&<PrimaryButton onPress={()=>router.push('/verify-phone')}>Verify phone</PrimaryButton>}{profile?.role==='member'?<PrimaryButton variant="outline" onPress={()=>router.push('/publisher-setup')}>Become a publisher</PrimaryButton>:<PrimaryButton onPress={()=>router.push('/my-listings')}>My listings</PrimaryButton>}<PrimaryButton variant="outline" onPress={()=>void signOut(true)}>Sign out all devices</PrimaryButton></Page>}
function Status({ok,label}:{ok:boolean;label:string}){return <View style={s.status}>{ok?<CheckCircle2 color={colors.green}/>:<CircleAlert color={colors.amber}/>}<Text style={s.statusText}>{ok?label:label.replace('verified','not verified')}</Text></View>}
const s=StyleSheet.create({title:{fontFamily:fonts.bold,fontSize:30,color:colors.ink},email:{fontFamily:fonts.regular,color:colors.slate,marginTop:5,marginBottom:24},card:{backgroundColor:colors.white,borderRadius:22,padding:22,gap:12,marginBottom:18},name:{fontFamily:fonts.semibold,fontSize:21,color:colors.ink},role:{fontFamily:fonts.medium,color:colors.slate,textTransform:'capitalize',marginBottom:8},status:{flexDirection:'row',alignItems:'center',gap:10},statusText:{fontFamily:fonts.medium,color:colors.ink}});
