import { Alert, Linking, StyleSheet, Text, TextInput, View } from 'react-native';
import { Mail, Phone } from 'lucide-react-native';
import { useState } from 'react';
import { Page } from '@/components/page';
import { PrimaryButton, inputStyle } from '@/components/ui';
import { agents } from '@/data/properties';
import { colors, fonts, shadow } from '@/theme/tokens';

export default function AgentsScreen() { const [query, setQuery] = useState(''); const matches = agents.filter((agent) => !query || [...agent.areas, agent.name, agent.agency].join(' ').toLowerCase().includes(query.toLowerCase())); return <Page back><Text style={styles.title}>Find an Agent</Text><Text style={styles.body}>Connect with a local specialist. Professional credentials are displayed as provided unless explicitly marked otherwise.</Text><TextInput placeholder="Search area, agent or agency" placeholderTextColor={colors.slate} value={query} onChangeText={setQuery} style={[inputStyle, { marginBottom: 24 }]} />{matches.map((agent) => <View key={agent.id} style={styles.card}><View style={styles.avatar}><Text style={styles.avatarText}>{agent.name[0]}</Text></View><Text style={styles.name}>{agent.name}</Text><Text style={styles.agency}>{agent.agency}</Text><Text style={styles.areas}>{agent.areas.join(' · ')}</Text><View style={styles.buttons}><PrimaryButton icon={<Phone color={colors.white} />} onPress={() => Linking.openURL(`tel:${agent.phone}`).catch(() => Alert.alert('Phone unavailable'))}>Call agent</PrimaryButton><PrimaryButton variant="outline" icon={<Mail color={colors.blue} />} onPress={() => Linking.openURL(`mailto:${agent.email}`).catch(() => Alert.alert('Email unavailable'))}>Email</PrimaryButton></View></View>)}</Page>; }
const styles = StyleSheet.create({ title: { fontFamily: fonts.bold, color: colors.ink, fontSize: 31 }, body: { fontFamily: fonts.regular, color: colors.slate, fontSize: 16, marginTop: 5, marginBottom: 22 }, card: { backgroundColor: colors.white, borderRadius: 26, padding: 24, marginBottom: 22, alignItems: 'center', borderWidth: 1, borderColor: colors.border, ...shadow }, avatar: { width: 82, height: 82, borderRadius: 41, backgroundColor: colors.softBlue, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontFamily: fonts.semibold, color: colors.blue, fontSize: 32 }, name: { fontFamily: fonts.bold, color: colors.ink, fontSize: 21, marginTop: 14 }, agency: { fontFamily: fonts.regular, color: colors.slate }, areas: { fontFamily: fonts.regular, color: colors.slate, fontSize: 13, marginTop: 10, textAlign: 'center' }, buttons: { width: '100%', gap: 10, marginTop: 20 } });
