import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { Field, PrimaryButton, inputStyle } from '@/components/ui';
import { FormScreen } from '@/components/form-screen';
import { useAuth } from '@/context/auth-context';
import { colors,fonts } from '@/theme/tokens';
export default function PublisherSetup(){const{auth,profile,setupPublisher}=useAuth();const[kind,setKind]=useState<'owner'|'agent'>('owner');const[agency,setAgency]=useState('');const[ffc,setFfc]=useState('');if(!auth){router.replace('/sign-in');return null;}const submit=async()=>{if(!profile?.verification.emailVerified)return Alert.alert('Confirm email first');const r=await setupPublisher(kind,agency,ffc);if(r.error)Alert.alert('Unable to continue',r.error);else router.replace(profile?.verification.phoneVerified?'/my-listings':'/verify-phone')};return <FormScreen title="Publisher profile" body="Choose how you list. Professional details are displayed as provided and are not independently verified in v1."><View style={s.row}>{(['owner','agent'] as const).map(v=><Pressable key={v} onPress={()=>setKind(v)} style={[s.choice,kind===v&&s.active]}><Text style={[s.text,kind===v&&s.activeText]}>{v==='owner'?'Private owner':'Estate agent'}</Text></Pressable>)}</View>{kind==='agent'&&<><Field label="Agency"><TextInput style={inputStyle} value={agency} onChangeText={setAgency}/></Field><Field label="PPRA / FFC number (unverified)"><TextInput style={inputStyle} value={ffc} onChangeText={setFfc}/></Field></>}<PrimaryButton onPress={submit}>Save publisher profile</PrimaryButton></FormScreen>}
const s=StyleSheet.create({row:{flexDirection:'row',gap:10,marginBottom:20},choice:{flex:1,padding:15,borderWidth:1,borderColor:colors.border,borderRadius:15},active:{backgroundColor:colors.blue,borderColor:colors.blue},text:{fontFamily:fonts.medium,color:colors.ink,textAlign:'center'},activeText:{color:colors.white}});
