import { useState } from 'react';
import { KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { Page } from '@/components/page';
import { Field, PrimaryButton, inputStyle } from '@/components/ui';
import { storage } from '@/lib/storage';
import { colors, fonts } from '@/theme/tokens';
import { validateValuation, type ValuationForm as Form } from '@/lib/valuation-validation';

const initial: Form = { name: '', email: '', phone: '', address: '', propertyType: '', bedrooms: '', bathrooms: '', notes: '' };
export default function ValuationScreen() {
  const [form, setForm] = useState(initial); const [errors, setErrors] = useState<ReturnType<typeof validateValuation>>({});
  const update = (key: keyof Form, value: string) => { setForm((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: undefined })); };
  const submit = async () => { const nextErrors = validateValuation(form); if (Object.keys(nextErrors).length) { setErrors(nextErrors); return; } await storage.saveValuation({ ...form, id: `valuation-${Date.now()}`, bedrooms: Number(form.bedrooms) || 0, bathrooms: Number(form.bathrooms) || 0, createdAt: new Date().toISOString() }); router.replace('/valuation-success'); };
  return <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><Page back><Text style={styles.title}>Get Home Valuation</Text><Text style={styles.body}>Tell us about your property and a local specialist will prepare a market appraisal.</Text><View style={styles.form}><Input label="Full name" field="name" form={form} errors={errors} update={update} /><Input label="Email address" field="email" form={form} errors={errors} update={update} keyboard="email-address" /><Input label="Phone number" field="phone" form={form} errors={errors} update={update} keyboard="phone-pad" /><Input label="Property address" field="address" form={form} errors={errors} update={update} /><Input label="Property type" field="propertyType" form={form} errors={errors} update={update} /><View style={styles.row}><View style={{ flex: 1 }}><Input label="Bedrooms" field="bedrooms" form={form} errors={errors} update={update} keyboard="number-pad" /></View><View style={{ flex: 1 }}><Input label="Bathrooms" field="bathrooms" form={form} errors={errors} update={update} keyboard="number-pad" /></View></View><Field label="Anything else we should know?"><TextInput multiline numberOfLines={4} value={form.notes} onChangeText={(value) => update('notes', value)} style={[inputStyle, styles.notes]} /></Field><PrimaryButton onPress={submit}>Request Valuation</PrimaryButton><Text style={styles.disclaimer}>This prototype stores your request on this device. It does not provide a legal or bank valuation.</Text></View></Page></KeyboardAvoidingView>;
}
function Input({ label, field, form, errors, update, keyboard }: { label: string; field: keyof Form; form: Form; errors: ReturnType<typeof validateValuation>; update: (key: keyof Form, value: string) => void; keyboard?: 'email-address' | 'phone-pad' | 'number-pad' }) { return <Field label={label} error={errors[field]}><TextInput value={form[field]} onChangeText={(value) => update(field, value)} keyboardType={keyboard} autoCapitalize={keyboard === 'email-address' ? 'none' : 'sentences'} style={inputStyle} /></Field>; }
const styles = StyleSheet.create({ title: { color: colors.ink, fontFamily: fonts.bold, fontSize: 31 }, body: { color: colors.slate, fontFamily: fonts.regular, fontSize: 16, lineHeight: 26, marginTop: 8, marginBottom: 28 }, form: { backgroundColor: colors.white, borderRadius: 28, padding: 22, borderWidth: 1, borderColor: colors.border }, row: { flexDirection: 'row', gap: 12 }, notes: { minHeight: 110, paddingTop: 14, textAlignVertical: 'top' }, disclaimer: { color: colors.slate, fontFamily: fonts.regular, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 14 } });
