import { useEffect, useState } from 'react';
import { Alert, Linking, Pressable, Share, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { useLocalSearchParams } from 'expo-router';
import { Bath, BedDouble, CarFront, Check, Heart, Mail, MapPin, Maximize, Phone, Share2 } from 'lucide-react-native';
import { Page } from '@/components/page';
import { Badge, EmptyState, PrimaryButton } from '@/components/ui';
import { useApp } from '@/context/app-context';
import { agents } from '@/data/properties';
import { formatPrice, localPropertyRepository } from '@/lib/property-repository';
import { colors, fonts, shadow } from '@/theme/tokens';
import type { Property } from '@/types';

async function openLink(url: string, label: string) { try { if (await Linking.canOpenURL(url)) await Linking.openURL(url); else Alert.alert(`${label} unavailable`, `This device cannot open ${label}.`); } catch { Alert.alert(`${label} unavailable`, 'Please try again on a configured device.'); } }

export default function PropertyDetails() {
  const { id } = useLocalSearchParams<{ id: string }>(); const [property, setProperty] = useState<Property>(); const [imageIndex, setImageIndex] = useState(0); const { favorites, toggleFavorite } = useApp();
  useEffect(() => { if (id) void localPropertyRepository.byId(id).then(setProperty); }, [id]);
  if (!property) return <Page back><EmptyState title="Property unavailable" body="This listing may have been removed or the link is incorrect." /></Page>;
  const agent = agents.find((item) => item.id === property.agentId)!; const saved = favorites.includes(property.id);
  return <Page back contentContainerStyle={styles.page}>
    <View style={styles.actions}><Pressable onPress={() => Share.share({ title: property.title, message: `${property.title} — ${formatPrice(property)}` })} style={styles.action}><Share2 size={20} color={colors.ink} /><Text style={styles.actionText}>Share</Text></Pressable><Pressable onPress={() => toggleFavorite(property.id)} style={styles.action}><Heart size={20} color={colors.ink} fill={saved ? colors.blue : 'transparent'} /><Text style={styles.actionText}>{saved ? 'Saved' : 'Save'}</Text></Pressable></View>
    <Image source={property.images[imageIndex].source} contentFit="cover" style={styles.hero} accessibilityLabel={property.images[imageIndex].alt} />
    <View style={styles.thumbs}>{property.images.map((image, index) => <Pressable key={image.id} onPress={() => setImageIndex(index)} style={[styles.thumbWrap, imageIndex === index && styles.thumbSelected]}><Image source={image.source} contentFit="cover" style={styles.thumb} accessibilityLabel={image.alt} /></Pressable>)}</View>
    <View style={styles.badges}><Badge>{property.mode === 'rent' ? 'For rent' : property.mode === 'commercial' ? 'Commercial' : 'For sale'}</Badge><Badge tone="soft">{property.type}</Badge></View>
    <Text style={styles.title}>{property.title}</Text><View style={styles.location}><MapPin color={colors.blue} size={28} /><Text style={styles.locationText}>{property.address}, {property.suburb}, {property.city}, {property.province}</Text></View>
    <View style={styles.priceBox}><Text style={styles.price}>{formatPrice(property)}</Text></View>
    <View style={styles.card}><View style={styles.specGrid}><Spec icon={<BedDouble />} value={property.features.bedrooms} label="Bedrooms" /><Spec icon={<Bath />} value={property.features.bathrooms} label="Bathrooms" /><Spec icon={<CarFront />} value={property.features.garages} label="Garages" /><Spec icon={<Maximize />} value={`${property.features.floorSize} m²`} label="Floor Size" /></View></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Property Description</Text><Text style={styles.body}>{property.description}</Text></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Features & Amenities</Text><View style={styles.amenities}>{property.amenities.map((amenity) => <View key={amenity.id} style={styles.amenity}><View style={styles.check}><Check size={14} color={colors.green} strokeWidth={3} /></View><Text style={styles.amenityText}>{amenity.label}</Text></View>)}</View></View>
    <View style={styles.agentCard}><View style={styles.agentTop}><Text style={styles.agentTopText}>Contact Agent</Text></View><View style={styles.avatar}><Text style={styles.avatarText}>{agent.name[0]}</Text></View><Text style={styles.agentName}>{agent.name}</Text><Text style={styles.agency}>{agent.agency}</Text><View style={styles.contactButtons}><PrimaryButton icon={<Phone color={colors.white} />} onPress={() => openLink(`tel:${agent.phone}`, 'Phone')}>{agent.phone.replace('+27', '+27 ')}</PrimaryButton><PrimaryButton variant="green" onPress={() => openLink(`https://wa.me/${agent.whatsapp}?text=${encodeURIComponent(`Hi ${agent.name}, I am interested in ${property.title}.`)}`, 'WhatsApp')}>WhatsApp</PrimaryButton><PrimaryButton variant="outline" icon={<Mail color={colors.blue} />} onPress={() => openLink(`mailto:${agent.email}?subject=${encodeURIComponent(property.title)}`, 'Email')}>Email Agent</PrimaryButton></View></View>
    <Pressable onPress={() => openLink(`https://maps.google.com/?q=${property.latitude},${property.longitude}`, 'Maps')} style={styles.map}><MapPin color={colors.white} size={32} /><Text style={styles.mapText}>View on Map</Text></Pressable>
  </Page>;
}
function Spec({ icon, value, label }: { icon: React.ReactNode; value: string | number; label: string }) { return <View style={styles.spec}><View style={styles.specIcon}>{icon}</View><View><Text style={styles.specValue}>{value}</Text><Text style={styles.specLabel}>{label}</Text></View></View>; }
const styles = StyleSheet.create({
  page: { paddingTop: 28, gap: 24 }, actions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 12 }, action: { flexDirection: 'row', gap: 8, alignItems: 'center', paddingHorizontal: 18, height: 48, borderRadius: 24, backgroundColor: colors.white, ...shadow }, actionText: { fontFamily: fonts.semibold, color: colors.ink }, hero: { width: '100%', height: 300, borderRadius: 28 }, thumbs: { flexDirection: 'row', gap: 14 }, thumbWrap: { borderRadius: 14, padding: 2, borderWidth: 2, borderColor: 'transparent' }, thumbSelected: { borderColor: colors.blue }, thumb: { width: 90, height: 65, borderRadius: 10 }, badges: { flexDirection: 'row', gap: 12 },
  title: { color: colors.ink, fontFamily: fonts.bold, fontSize: 38, lineHeight: 47, letterSpacing: -1.8 }, location: { flexDirection: 'row', gap: 12, alignItems: 'center' }, locationText: { flex: 1, color: colors.slate, fontFamily: fonts.regular, fontSize: 17, lineHeight: 27 }, priceBox: { padding: 28, borderRadius: 26, backgroundColor: colors.softBlue, borderWidth: 1, borderColor: '#D9E1F6' }, price: { color: colors.blue, fontFamily: fonts.bold, fontSize: 37 },
  card: { backgroundColor: colors.white, borderRadius: 28, padding: 28, borderWidth: 1, borderColor: colors.border, ...shadow }, cardTitle: { fontFamily: fonts.semibold, color: colors.ink, fontSize: 24, marginBottom: 22 }, body: { fontFamily: fonts.regular, color: colors.slate, fontSize: 17, lineHeight: 29 }, specGrid: { flexDirection: 'row', flexWrap: 'wrap', rowGap: 26 }, spec: { width: '50%', flexDirection: 'row', alignItems: 'center', gap: 12 }, specIcon: { width: 54, height: 54, borderRadius: 27, backgroundColor: colors.softBlue, alignItems: 'center', justifyContent: 'center' }, specValue: { fontFamily: fonts.bold, color: colors.ink, fontSize: 22 }, specLabel: { fontFamily: fonts.regular, color: colors.slate, fontSize: 13 },
  amenities: { gap: 19 }, amenity: { flexDirection: 'row', alignItems: 'center', gap: 14 }, check: { width: 27, height: 27, borderRadius: 14, borderWidth: 2, borderColor: colors.green, alignItems: 'center', justifyContent: 'center' }, amenityText: { fontFamily: fonts.medium, color: colors.ink, fontSize: 16 },
  agentCard: { backgroundColor: colors.white, borderRadius: 28, overflow: 'hidden', alignItems: 'center', borderWidth: 1, borderColor: colors.border, ...shadow }, agentTop: { width: '100%', height: 120, backgroundColor: colors.ink, alignItems: 'center', paddingTop: 24 }, agentTopText: { color: colors.white, fontFamily: fonts.semibold, fontSize: 19 }, avatar: { width: 118, height: 118, marginTop: -58, borderRadius: 59, borderWidth: 6, borderColor: colors.white, backgroundColor: '#E7ECFF', alignItems: 'center', justifyContent: 'center', ...shadow }, avatarText: { color: colors.blue, fontFamily: fonts.medium, fontSize: 42 }, agentName: { fontFamily: fonts.bold, color: colors.ink, fontSize: 22, marginTop: 22 }, agency: { color: colors.slate, fontFamily: fonts.regular, fontSize: 16 }, contactButtons: { width: '100%', padding: 24, gap: 13 },
  map: { height: 260, borderRadius: 28, backgroundColor: '#C7D1E2', alignItems: 'center', justifyContent: 'center', gap: 14 }, mapText: { backgroundColor: colors.white, color: colors.ink, borderRadius: 999, paddingHorizontal: 24, paddingVertical: 13, fontFamily: fonts.semibold, fontSize: 18 },
});
